apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  labels:
    app: devops-task3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-task3
  template:
    metadata:
      labels:
        app: devops-task3
    spec:
      containers:
        - name: devops-task3-cd
          image: zboromir/devops_task3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-task3-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: devops-task3
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer
